### ISSUE TITLE
Wrong Information in Readme.md

### ISSUE THREAD

**Issue by Alok5102R** [singhnitin77/Gradientify#30]
You'd provided wrong information in "Readme.md"
It says, a person can add gradients by following the steps and contribute to this repository.
But, instead you are putting invalid label and closing PR.
What's that means @singhnitin77 ?

**Comment by singhnitin77** [comment]
Accepting quality PRs for Hactoberfest. Adding gradients is one of many ways to contribute but not the only way. It was mentioned way before Hacktoberfest, when gradientify launched thus no wrong information is provided.

If you want to work on some exciting or unique feature PRs are always welcome : ) Thanks
@Alok5102R
